---
title: "p8106_hw1_qw2331"
output: github_document
---

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
library(summarytools)
library(corrplot)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%",
  message = FALSE,
  warning = FALSE)

# Set options for dfSummary()
st_options(
  plain.ascii = FALSE,
  style = "rmarkdown",
  dfSummary.silent = TRUE,
  footnote = NA,
  subtitle.emphasis = FALSE
)
```


### Data Overview
```{r}
trainHousing <- read_csv("./data/housing_training.csv")
testHousing <- read_csv("./data/housing_test.csv")

# A brief overview of train data
dfSummary(trainHousing)
```
From the summary, there are `25` predictors with `1` response `Sale_Price` in the train data and each column has `1440` observations without missing values. And there are `4` categorical predictors so additional transformations are needed as they are difficult to interpret and potentially causing other problems.

### Data Preprocessing
```{r, fig.width = 12}
# Convert categorical into dummy variables
train_x <- model.matrix(Sale_Price ~ ., trainHousing)[ ,-1]
train_y <- trainHousing$Sale_Price
test_x <- model.matrix(Sale_Price ~ ., testHousing)[ ,-1]
test_y <- testHousing$Sale_Price

corrplot(cor(train_x), 
         type = "upper", tl.cex = .8, tl.col = "black")
```

